#include "Sentinel/Audit/AuditService.hpp"
#include <sstream>
#include <stdexcept>
namespace sentinel {
static std::vector<std::byte> bytesOf(const std::string&s){return {reinterpret_cast<const std::byte*>(s.data()),reinterpret_cast<const std::byte*>(s.data()+s.size())};}
Hash256 AuditService::GetCurrentHead(){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"SELECT record_hash FROM audit_records ORDER BY sequence DESC LIMIT 1",-1,&s,nullptr);Hash256 h{};if(sqlite3_step(s)==SQLITE_ROW){auto p=(const char*)sqlite3_column_text(s,0);if(auto v=Hash256::FromHex(p))h=*v;}sqlite3_finalize(s);return h;}
AuditId AuditService::Append(const AuditEvent&e){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"SELECT COALESCE(MAX(sequence),0),COALESCE((SELECT record_hash FROM audit_records ORDER BY sequence DESC LIMIT 1),'0000000000000000000000000000000000000000000000000000000000000000') FROM audit_records",-1,&s,nullptr);uint64_t seq=1;std::string prev(64,'0');if(sqlite3_step(s)==SQLITE_ROW){seq=(uint64_t)sqlite3_column_int64(s,0)+1;prev=(const char*)sqlite3_column_text(s,1);}sqlite3_finalize(s);auto id=AuditId::Random();auto ts=ToIso8601Utc(NowUtc());auto actor=e.actor.ToString();std::string target=e.targetId.value_or("");std::string canon="audit-v1|"+std::to_string(seq)+"|"+ts+"|"+actor+"|"+std::to_string((uint32_t)e.action)+"|"+e.targetType+"|"+target+"|"+prev;auto rh=hash_.Sha256(bytesOf(canon)).ToHex();sqlite3_prepare_v2(db_.Handle(),"INSERT INTO audit_records(id,sequence,timestamp,actor_id,action,target_type,target_id,metadata,previous_hash,record_hash) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)",-1,&s,nullptr);auto sid=id.ToString();sqlite3_bind_text(s,1,sid.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int64(s,2,(sqlite3_int64)seq);sqlite3_bind_text(s,3,ts.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,actor.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,5,(int)e.action);sqlite3_bind_text(s,6,e.targetType.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,7,target.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_blob(s,8,e.metadata.data(),(int)e.metadata.size(),SQLITE_TRANSIENT);sqlite3_bind_text(s,9,prev.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,10,rh.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error("audit insert failed");}sqlite3_finalize(s);return id;}
bool AuditService::VerifyChain(){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"SELECT sequence,timestamp,actor_id,action,target_type,target_id,previous_hash,record_hash FROM audit_records ORDER BY sequence ASC",-1,&s,nullptr);std::string prev(64,'0');uint64_t expect=1;bool ok=true;while(sqlite3_step(s)==SQLITE_ROW){uint64_t seq=sqlite3_column_int64(s,0);auto ts=(const char*)sqlite3_column_text(s,1);auto actor=(const char*)sqlite3_column_text(s,2);auto action=sqlite3_column_int(s,3);auto type=(const char*)sqlite3_column_text(s,4);auto tid=(const char*)sqlite3_column_text(s,5);auto storedPrev=(const char*)sqlite3_column_text(s,6);auto storedHash=(const char*)sqlite3_column_text(s,7);if(seq!=expect||prev!=storedPrev){ok=false;break;}std::string canon="audit-v1|"+std::to_string(seq)+"|"+ts+"|"+actor+"|"+std::to_string(action)+"|"+type+"|"+(tid?tid:"")+"|"+prev;auto calc=hash_.Sha256(bytesOf(canon)).ToHex();if(calc!=storedHash){ok=false;break;}prev=storedHash;++expect;}sqlite3_finalize(s);return ok;}
}
