#include "Sentinel/Core/CaseRepository.hpp"
#include <stdexcept>
namespace sentinel {
static CaseRecord ReadCase(sqlite3_stmt* s){CaseRecord r; r.id=*CaseId::Parse((const char*)sqlite3_column_text(s,0));r.caseNumber=(const char*)sqlite3_column_text(s,1);r.title=(const char*)sqlite3_column_text(s,2);r.description=(const char*)sqlite3_column_text(s,3);r.status=(CaseStatus)sqlite3_column_int(s,4);r.createdBy=*UserId::Parse((const char*)sqlite3_column_text(s,5));return r;}
void SqliteCaseRepository::Insert(const CaseRecord&r){sqlite3_stmt*s{};const char*q="INSERT INTO cases(id,case_number,title,description,status,created_by,created_at,modified_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8)";if(sqlite3_prepare_v2(db_.Handle(),q,-1,&s,nullptr)!=SQLITE_OK)throw std::runtime_error("prepare case insert failed");auto id=r.id.ToString(),u=r.createdBy.ToString(),ca=ToIso8601Utc(r.createdAt),ma=ToIso8601Utc(r.modifiedAt);sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,r.caseNumber.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,r.title.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,r.description.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,5,(int)r.status);sqlite3_bind_text(s,6,u.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,7,ca.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,8,ma.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error("insert case failed");}sqlite3_finalize(s);}
std::optional<CaseRecord> SqliteCaseRepository::Get(const CaseId&id){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"SELECT id,case_number,title,description,status,created_by,created_at,modified_at FROM cases WHERE id=?1",-1,&s,nullptr);auto sid=id.ToString();sqlite3_bind_text(s,1,sid.c_str(),-1,SQLITE_TRANSIENT);std::optional<CaseRecord> out;if(sqlite3_step(s)==SQLITE_ROW)out=ReadCase(s);sqlite3_finalize(s);return out;}
std::vector<CaseRecord> SqliteCaseRepository::List(){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"SELECT id,case_number,title,description,status,created_by,created_at,modified_at FROM cases ORDER BY modified_at DESC",-1,&s,nullptr);std::vector<CaseRecord> out;while(sqlite3_step(s)==SQLITE_ROW)out.push_back(ReadCase(s));sqlite3_finalize(s);return out;}
void SqliteCaseRepository::Update(const CaseRecord&r){sqlite3_stmt*s{};sqlite3_prepare_v2(db_.Handle(),"UPDATE cases SET case_number=?2,title=?3,description=?4,status=?5,modified_at=?6 WHERE id=?1",-1,&s,nullptr);auto id=r.id.ToString(),ma=ToIso8601Utc(r.modifiedAt);sqlite3_bind_text(s,1,id.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,2,r.caseNumber.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,3,r.title.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_text(s,4,r.description.c_str(),-1,SQLITE_TRANSIENT);sqlite3_bind_int(s,5,(int)r.status);sqlite3_bind_text(s,6,ma.c_str(),-1,SQLITE_TRANSIENT);if(sqlite3_step(s)!=SQLITE_DONE){sqlite3_finalize(s);throw std::runtime_error("update case failed");}sqlite3_finalize(s);}
}
